name: narr
description: NARR

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.1.0
#  utils
  permission_handler: ^8.1.1
  photo_view: ^0.13.0
#  another_flushbar: ^1.10.23
  charts_flutter: ^0.12.0
  numberpicker: ^2.1.1
  flutter_rating_bar: ^4.0.0
  rflutter_alert: ^2.0.2
  currency_text_input_formatter: ^2.0.1
  multi_select_flutter: ^4.0.0
  flutter_typeahead: ^3.1.3
  flutter_speed_dial: ^3.0.5
  carousel_slider: ^4.0.0
  flutter_tags: ^0.4.9+1
  fluttertoast: ^8.0.7
  argon_buttons_flutter: ^1.1.0
  clipboard: ^0.1.3
  flutter_svg: ^0.22.0
  percent_indicator: ^3.0.1
  shimmer: ^2.0.0
#  internet-web-url
  http: ^0.13.3
  dio: ^4.0.0
  flutter_inappwebview: ^5.3.2
  socket_io_client: ^1.0.1
  url_launcher: ^6.0.7
  flutter_html: ^2.1.0
#state management
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  mobx_codegen: ^2.0.1+3
#  path/storage
  path: ^1.8.0
  path_provider: ^2.0.2
  ext_storage: ^1.0.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
#  picker
  file_picker: ^3.0.3
  image_picker: ^0.8.1+1
# payments
  flutter_paystack: ^1.0.5+1
  hive_generator: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5

flutter:

  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/jpg/
    - assets/svg/
    - assets/json/

  fonts:
    - family: CourrierPrime
      fonts:
        - asset: assets/fonts/CourierPrime-Regular.ttf

  